-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgK3T8sMIDVmlnC1SI
IAr+6UyWDZYsg+VAUa/nWt5zJzegCgYIKoZIzj0DAQehRANCAATDPqnnk3nZVabE
78v12GBRWLyGaVHhlMGAS7FkWFFE5mgVVA3uo6SoKyFoHxtrgsFy8dnlifminunh
r5TtAyca
-----END PRIVATE KEY-----